#!/usr/bin/env python3
"""
build_dossier.py

Turn recon pipeline output into a per-target dossier the AI system consumes
(BUG-BOUNTY-RECON/companies/<slug>/). Fills the *machine facts* — assets.md
(tech fingerprint = the CHECKLIST router signal), sitemap.md, apis.md — from:
  - recon.sh output   (recon/<program>/<date>/: domains.csv, live_all.txt, js/<host>/)
  - APK surface maps  (apk_surface_map jsonl)   [optional]

    python3 scripts/build_dossier.py under-armour \
        --recon-dir recon/under-armour/2026-09-25 \
        --surface drill/2026-09-25/com.ua.shop/surface.jsonl \
        --out ~/bug-bounty-recon/companies/under-armour

Regenerates assets/sitemap/apis (marked AUTOGENERATED). Never overwrites a
hand-written strategy.md / findings.md — only creates them from a stub if absent.

Tech fingerprint uses httpx -td if present (falls back to headers/JS heuristics).
Pure stdlib otherwise.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

# --- extraction patterns -----------------------------------------------------
ABS_URL = re.compile(r'https?://[A-Za-z0-9.\-]+(?:/[A-Za-z0-9_./%{}:$\-]*)?')
PATH_LIT = re.compile(r'["\'`](/(?:api|v\d|graphql|rest|internal|auth|oauth|user|users|account|accounts|orders?|admin|gateway)[A-Za-z0-9_./%{}:$\-]*)["\'`]')
FETCHY = re.compile(r'(?:fetch|axios|\.(?:get|post|put|patch|delete))\(\s*["\'`]([^"\'`]+)["\'`]', re.I)
UUID = re.compile(r'\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b', re.I)

SIGNALS = {
    "auth_login":  re.compile(r'\b(login|signin|sign-in|log-?in|authenticate)\b', re.I),
    "password_reset": re.compile(r'(forgot.?password|reset.?password|password.?reset)', re.I),
    "mfa_otp":     re.compile(r'\b(mfa|otp|2fa|two.?factor|verification.?code)\b', re.I),
    "oauth_sso":   re.compile(r'(redirect_uri|client_id|response_type|oauth2?|saml|sso)', re.I),
    "jwt":         re.compile(r'(eyJ[A-Za-z0-9_-]{10,}|bearer |authorization)', re.I),
    "graphql":     re.compile(r'(/graphql|__typename|__schema|operationName|persistedQuery)', re.I),
    "firebase":    re.compile(r'([a-z0-9-]+\.firebaseio\.com|firebaseapp\.com|firebase)', re.I),
    "s3_gcs":      re.compile(r'(s3[.\-][a-z0-9.\-]*amazonaws\.com|storage\.googleapis\.com|\.appspot\.com)', re.I),
    "roles_admin": re.compile(r'\b(is_?admin|role|permission|isAdmin|owner_id|tenant|org_id|team_id)\b', re.I),
    "money_flow":  re.compile(r'\b(checkout|coupon|promo|referral|balance|wallet|credit|payment|refund)\b', re.I),
    "file_param":  re.compile(r'[?&](file|path|download|template|doc|attachment|report)=', re.I),
    "url_param":   re.compile(r'[?&](url|uri|dest|redirect|callback|feed|webhook|image_url|next)=', re.I),
}


def read_domains(recon_dir: Path):
    """(hosts, wildcards) from domains.csv."""
    hosts, wild = [], []
    f = recon_dir / "domains.csv"
    if f.exists():
        for row in csv.DictReader(f.open()):
            (wild if row.get("kind") == "wildcard" else hosts).append(row["host"])
    return hosts, wild


def read_live(recon_dir: Path):
    f = recon_dir / "live_all.txt"
    return [l.strip() for l in f.read_text().splitlines()] if f.exists() else []


def httpx_tech(hosts):
    """{url: 'Tech, Tech'} via httpx -td, or {} if unavailable."""
    if not (hosts and shutil.which("httpx")):
        return {}
    try:
        r = subprocess.run(["httpx", "-silent", "-td", "-sc", "-title", "-no-color"],
                           input="\n".join(hosts), capture_output=True, text=True, timeout=600)
    except Exception:
        return {}
    out = {}
    for line in r.stdout.splitlines():
        parts = line.split()
        if not parts:
            continue
        url = parts[0]
        tech = re.findall(r'\[([^\]]*)\]', line)
        out[url] = " · ".join(t for t in tech if t)
    return out


def scan_js(recon_dir: Path):
    """Walk js/<host>/*.js → endpoints, graphql eps, signals, sample UUIDs."""
    endpoints, gql, uuids = set(), set(), set()
    sig = defaultdict(int)
    jsdir = recon_dir / "js"
    if not jsdir.exists():
        return endpoints, gql, sig, uuids
    for jf in jsdir.rglob("*.js"):
        try:
            t = jf.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        for m in FETCHY.findall(t):
            if m.startswith(("/", "http")):
                endpoints.add(m.split("?")[0][:120])
        for m in PATH_LIT.findall(t):
            endpoints.add(m.split("?")[0][:120])
        for u in ABS_URL.findall(t):
            if "/graphql" in u:
                gql.add(u.split("?")[0])
        for name, rx in SIGNALS.items():
            if rx.search(t):
                sig[name] += 1
        for u in UUID.findall(t)[:3]:
            uuids.add(u)
    return endpoints, gql, sig, uuids


def surface_signals(surface: Path):
    """Pull mobile signals + endpoints from an apk_surface_map jsonl."""
    info = {"exported": 0, "deeplinks": [], "providers": 0, "gql": 0, "fb": 0, "apis": []}
    if not surface or not surface.exists():
        return info
    for line in surface.read_text().splitlines():
        try:
            d = json.loads(line)
        except Exception:
            continue
        info["exported"] += len(d.get("exported_components", []) or []) or d.get("exported_total", 0) or 0
        info["deeplinks"] += (d.get("deeplinks") or [])[:20]
        info["apis"] += (d.get("api_endpoints") or d.get("apis") or [])[:100]
        info["gql"] += d.get("graphql_total", 0) or (1 if d.get("graphql") else 0)
        info["fb"] += d.get("firebase_rtdb", 0) or 0
    return info


def autogen_header(kind):
    return (f"# {kind} — AUTOGENERATED by build_dossier.py ({date.today().isoformat()})\n"
            f"> Machine facts. Regenerate freely. Hand-edited notes go in strategy.md.\n\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="Build a per-target dossier from recon output.")
    ap.add_argument("slug", help="company slug, e.g. under-armour")
    ap.add_argument("--recon-dir", type=Path, help="recon/<program>/<date>/ from recon.sh")
    ap.add_argument("--surface", type=Path, help="apk_surface_map .jsonl (optional)")
    ap.add_argument("--out", type=Path, required=True, help="companies/<slug> dir to write")
    ap.add_argument("--no-httpx", action="store_true", help="skip httpx tech-detect")
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    hosts = wild = []
    live = []
    if args.recon_dir and args.recon_dir.exists():
        hosts, wild = read_domains(args.recon_dir)
        live = read_live(args.recon_dir)
    tech = {} if args.no_httpx else httpx_tech(live)
    endpoints, gql, sig, uuids = scan_js(args.recon_dir) if args.recon_dir else (set(), set(), {}, set())
    surf = surface_signals(args.surface)
    if surf["gql"]:
        gql.add("(APK) GraphQL client present")

    # ---- sitemap.md ----
    sm = [autogen_header("sitemap — " + args.slug)]
    sm.append(f"In-scope: {len(hosts)} host(s) + {len(wild)} wildcard(s). Live: {len(live)}.\n")
    if wild:
        sm.append("**Wildcards (enum roots):** " + ", ".join(f"`{w}`" for w in wild) + "\n")
    sm.append("\n## Live hosts\n| host | status/tech |\n|---|---|")
    for u in sorted(live):
        sm.append(f"| {u} | {tech.get(u, '')} |")
    (args.out / "sitemap.md").write_text("\n".join(sm) + "\n", encoding="utf-8")

    # ---- apis.md ----
    ap_md = [autogen_header("apis — " + args.slug)]
    if gql:
        ap_md.append("## GraphQL\n" + "\n".join(f"- `{g}`" for g in sorted(gql)) + "\n")
    ap_md.append(f"## Endpoints from JS ({len(endpoints)})  → IDOR/authz/injection hunting list")
    for e in sorted(endpoints):
        ap_md.append(f"- `{e}`")
    if surf["apis"]:
        ap_md.append(f"\n## Endpoints from APK surface ({len(set(surf['apis']))})")
        for e in sorted(set(surf["apis"]))[:200]:
            ap_md.append(f"- `{e}`")
    if uuids:
        ap_md.append("\n## Sample object IDs seen (for IDOR swap)\n" +
                     "\n".join(f"- `{u}`" for u in sorted(uuids)))
    (args.out / "apis.md").write_text("\n".join(ap_md) + "\n", encoding="utf-8")

    # ---- assets.md (the fingerprint that drives CHECKLIST) ----
    present = [k for k, v in sig.items() if v]
    fp = [autogen_header("assets — " + args.slug)]
    fp.append("## Detected signals → run these playbooks (see ../../CHECKLIST.md)")
    rules = {
        "auth_login": "access-control-and-auth (auth, session)",
        "password_reset": "access-control-and-auth (password-reset ATO)",
        "mfa_otp": "access-control-and-auth (MFA/OTP bypass)",
        "oauth_sso": "access-control-and-auth (OAuth/SSO)",
        "jwt": "access-control-and-auth (JWT)",
        "graphql": "graphql + access-control-and-auth (IDOR)",
        "firebase": "recon-driven (Firebase /.json)",
        "s3_gcs": "recon-driven (bucket read/write/takeover)",
        "roles_admin": "access-control-and-auth (priv-esc/mass-assignment)",
        "money_flow": "access-control-and-auth (business logic/race)",
        "file_param": "path-traversal",
        "url_param": "injection (SSRF)",
    }
    for k in present:
        fp.append(f"- **{k}** ({sig[k]} hits) → {rules.get(k, '?')}")
    if gql:
        fp.append("- **graphql endpoint** → graphql + IDOR")
    if surf["exported"] or surf["deeplinks"] or surf["providers"]:
        fp.append(f"- **mobile** (exported={surf['exported']}, deeplinks={len(surf['deeplinks'])}, "
                  f"fb_rtdb={surf['fb']}) → mobile")
    fp.append("\n## Tech stack (httpx -td)")
    seen_tech = sorted({t for t in tech.values() if t})
    fp += [f"- {t}" for t in seen_tech] or ["- (httpx unavailable or no detections)"]
    fp.append("\n## Notes")
    fp.append("- Object IDs: see apis.md sample UUIDs / endpoint `{id}` params.")
    fp.append("- Fill auth/roles/money specifics by hand in strategy.md as confirmed.")
    (args.out / "assets.md").write_text("\n".join(fp) + "\n", encoding="utf-8")

    # ---- strategy.md / findings.md: create from stub only if missing ----
    if not (args.out / "strategy.md").exists():
        (args.out / "strategy.md").write_text(
            f"# strategy — {args.slug} (living log)\n> Read FIRST. Hypotheses, tried→outcome (dedup memory), next actions.\n\n"
            f"## Scope & rules\n- <program link> · bounty <y/n> · special rules <...>\n\n"
            f"## Leads (ranked)\n1. <lead> — playbook: <name> — status: open\n\n"
            f"## Tried → outcome (never re-tread)\n- \n\n## Next actions\n- [ ] \n", encoding="utf-8")
    if not (args.out / "findings.md").exists():
        (args.out / "findings.md").write_text(
            f"# findings — {args.slug}\n> One block per candidate (format per ../../AI-RULES.md). Human verifies + submits.\n", encoding="utf-8")

    print(f"dossier written: {args.out}/")
    print(f"  live={len(live)} tech={len(seen_tech)} endpoints={len(endpoints)} "
          f"gql={len(gql)} signals={present}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
